version: '3'

services:
  orderapi:
    image: orderapi
    ports: 
     - "8003:80"
    build:
      context: .
      dockerfile: OrderApi\Dockerfile

  customerapi:
    image: customerapi
    ports: 
     - "8000:80"
    build:
      context: .
      dockerfile: CustomerApi\Dockerfile

  productapi:
    image: productapi
    ports: 
    - "8002:80"
    build:
      context: .
      dockerfile: ProductApi\Dockerfile

